// Render the actual bundled webview with synthetic state in isolated Chrome.
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {execFile}=require('node:child_process'),run=require('node:util').promisify(execFile);
(async()=>{
 const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts','support-ui');await fs.mkdir(out,{recursive:true});
 const profile=await fs.mkdtemp(path.join(os.tmpdir(),'agent-pet-webview-'));
 const template=await fs.readFile(path.join(root,'src/support.html'),'utf8'),script=await fs.readFile(path.join(root,'src/support-ui.js'),'utf8');
 try {for(const tab of (process.argv.length>2?process.argv.slice(2):['setup','connections','diagnostics','narrow-tr'])){
 const state={generatedAt:Date.now(),language:tab==='narrow-tr'?'tr':'en',tab:tab==='narrow-tr'?'connections':tab,completed:false,extension:{loaded:'0.16.0',installed:'0.16.0'},system:{platform:'darwin',arch:'arm64',release:'25.0.0',vscode:'1.110.0',supported:true},helper:{status:'connected',version:'0.16.0',notifications:0,waitingNotifications:false},agents:[{name:'Codex',installed:true,version:'1.0'},{name:'Claude Code',installed:false,version:null}],records:[{agent:'Codex',status:'readable'},{agent:'Claude Code',status:'missing'}],tracking:true,publishing:true,workspaceOpen:true,windows:[{id:'client-1-abc.json',name:'Website',version:'0.16.0',connected:true,current:true,focused:true,tracking:true,chats:3,updatedAt:Date.now()},{id:'client-2-def.json',name:'Mobile App',version:'0.14.2',connected:false,current:false,focused:false,tracking:true,chats:1,updatedAt:Date.now()-28000}],errors:[]};
 const bootstrap=`const fixture=${JSON.stringify(state)},initialTab=fixture.tab;let copied=false;const emit=()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'state',state:fixture}}));window.acquireVsCodeApi=()=>({postMessage:m=>{if(m.action==='tab')fixture.tab=m.tab;if(m.action==='copy'){copied=true;window.dispatchEvent(new MessageEvent('message',{data:{type:'copied'}}));}queueMicrotask(emit);}});`;
 const checks=`setTimeout(async()=>{try{const check=(v,s)=>{if(!v)throw Error(s)};const step=()=>new Promise(r=>setTimeout(r,0));check(document.querySelectorAll('section:not([hidden])').length===1,'one tab');document.getElementById('tab-diagnostics').click();await step();check(!document.getElementById('diagnostics').hidden,'tab navigation');document.querySelector('#diagnostics [data-action=copy]').click();await step();check(copied&&document.getElementById('feedback').textContent,'copy feedback');fixture.tab='connections';fixture.windows[0].name='<img src=x onerror=alert(1)>';emit();check(!document.querySelector('#connections img'),'escape workspace name');fixture.windows[0].name='Website';fixture.windows=[];emit();check(document.querySelector('#connections .empty'),'empty state');fixture.windows=${JSON.stringify(state.windows)};fixture.helper.status='unknown';emit();check(!document.getElementById('health').textContent.includes('not running'),'unknown helper is not stopped');fixture.helper.status='connected';fixture.tab=initialTab;emit();document.getElementById('feedback').textContent='';check(document.documentElement.scrollWidth<=innerWidth,'no page overflow');document.body.dataset.test='passed';}catch(e){document.body.dataset.test='failed: '+e.message;}},30);`;
 const html=template.replaceAll('__NONCE__','testnonce').replace('__SCRIPT__',bootstrap+'\n'+script+'\n'+checks);
 const file=path.join(out,tab+'.html');await fs.writeFile(file,html);
 const {stdout}=await run('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless','--disable-gpu','--no-first-run','--no-default-browser-check','--user-data-dir='+profile,'--window-size='+(tab==='narrow-tr'?'600,1200':tab==='connections'?'1200,800':'1200,1120'),'--virtual-time-budget=1500','--screenshot='+path.join(out,tab+'.png'),'--dump-dom','file://'+file],{timeout:25000,maxBuffer:2*1024*1024});
 assert.match(stdout,/data-test="passed"/,stdout.match(/data-test="[^"]*"/)?.[0]||'No test result');console.log('PASS: '+tab+' renders; tabs, copy feedback, escaping, empty state, unavailable helper and overflow checks');
 }}finally{await fs.rm(profile,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
